---
version: 2
updates:
  - package-ecosystem: "devcontainers"
    # Look for a `devcontainer.json` in the `root` directory
    directory: "/"
    schedule:
      interval: "monthly"
  
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
